# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97a9e06f07337b7de55ff66555f7e69504e433768c6e600239964c73fd4cfb83e9b5cf5d657a655522d11ce56570770c735183381e9d6c9827baee4f979d9255

test:
  secret_key_base: 65d58be7d5363452aad8c8400c418f215131a13195adaa2a0a89e898063e78c580e78a5ad0713be876d1c9d416c3d409acc8ba163e89b584cbd6b0af64b78558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
